### ISSUE TITLE
Halle H fehlt in der englischen Version

### ISSUE THREAD

**Issue by thies23** [c3nav/c3nav-33c3#2]
In der deutschen Version ist Halle H verfügbar, in der Englischen fehlt diese.

**Comment by codingcatgirl** [comment]
Nicht wirklich, die autocompletion ist nur murks. gib „hh“ ein, dann erscheint sie auch da. wird demnächst™ gefixt, wenn die karten vollständig sind.

**Comment by nomoketo** [comment]
@c3nav
