### ISSUE TITLE
How to find out coordinates on the map?

### ISSUE THREAD

**Issue by Profpatsch** [c3nav/c3nav-33c3#7]
I’d like to add our assembl[y|ies].

**Comment by codingcatgirl** [comment]
use the editor to add it. :)

**Comment by Profpatsch** [comment]
I’m not sure in which menu assemblies go …

**Comment by Profpatsch** [comment]
If found it in location areas, but I’m not sure how I managed to confirm the poligon (the save button is not displayed until then, it should probably be greyed-out instead.

![screenshot](https://cloud.githubusercontent.com/assets/3153638/21502141/08573356-cc4e-11e6-8fa3-928867062142.png)

**Comment by Profpatsch** [comment]
Now it wants OAuth access, but it looks like it requires read & write access to *all* of my repositories. oO

![screenshot](https://cloud.githubusercontent.com/assets/3153638/21502157/2cde2914-cc4e-11e6-941a-1f5a673cf1d1.png)

**Comment by codingcatgirl** [comment]
we will add assembly ourselves in cooperation with the assemblies team :)
